# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      show-details: when-authorized
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customerGroup
  application:
    name: customerManagement
  jmx:
    enabled: false
  messages:
    basename: i18n/messages
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: customerManagement
      host: localhost # Mongo server host.
      password:
      port: 27017 # Mongo server port.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

server:
  servlet:
    session:
      cookie:
        http-only: true
